server:
  port: 8084

spring:
  application:
    name: standings-service
  datasource:
    url: jdbc:mysql://standings-db:3306/standings_db?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Queue configurations
queue:
  race-results-update:
    name: race-results-update-queue
  driver-update:
    name: driver-update-queue  
  team-update:
    name: team-update-queue