apiVersion: v1
kind: ConfigMap
metadata:
  name: f1-app-config
  namespace: f1-app
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  MYSQL_ROOT_PASSWORD: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: f1-app-secrets
  namespace: f1-app
type: Opaque
data:
  mysql-root-password: cm9vdA== # base64 encoded "root"
  rabbitmq-default-user: Z3Vlc3Q= # base64 encoded "guest" 
  rabbitmq-default-pass: Z3Vlc3Q= # base64 encoded "guest" 