apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: f1-app
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: eureka-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: f1-app-config
              key: SPRING_PROFILES_ACTIVE
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 40
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: f1-app
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  type: ClusterIP 